# Generated by Django 6.1.1 on 2026-09-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='reconciler.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('location_id_raw', models.CharField(blank=True, max_length=255)),
                ('value_raw', models.TextField(blank=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('raw_row', models.JSONField(default=dict)),
                ('import_errors', models.JSONField(default=list)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_a_records', to='reconciler.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_a_records', to='reconciler.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref_raw', models.CharField(blank=True, max_length=255)),
                ('record_ref_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('location_id_raw', models.CharField(blank=True, max_length=255)),
                ('value_raw', models.TextField(blank=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('raw_row', models.JSONField(default=dict)),
                ('import_errors', models.JSONField(default=list)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_b_entries', to='reconciler.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_b_entries', to='reconciler.organization')),
            ],
        ),
    ]
